---
- name: Configure linux desktop host.
  hosts: all
  become: true
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Ensure git is installed.
      ansible.builtin.package:
        name: git
        state: present
      tags:
        - dotfiles

  roles:
    - role: xiple.rpmfusion
      tags:
        - rpmfusion

    - role: xiple.vscode
      tags:
        - vscode

    - role: xiple.tailscale
      tags:
        - tailscale

    - role: xiple.tlp
      tags:
        - tlp

    - role: xiple.veracrypt
      tags:
        - veracrypt

    # To prevent conflicts, install only one of:
    #   - tailscale
    #   - nordvpn
    #
    # - role: xiple.nordvpn
    #   tags:
    #     - nordvpn

    - role: geerlingguy.dotfiles
      become: false
      tags:
        - dotfiles

    - role: geerlingguy.docker
      tags:
        - docker

  tasks:
    - name: Import main tasks
      ansible.builtin.import_tasks: tasks/main.yml
      tags:
        - main

    - name: Import Gnome tasks
      ansible.builtin.import_tasks: tasks/gnome.yml
      become: false
      tags:
        - gnome

    - name: Import virtualization tasks
      ansible.builtin.import_tasks: tasks/virtualization.yml
      tags:
        - virt
