---
roles:
  - name: geerlingguy.docker
    version: 7.8.0

  - name: geerlingguy.dotfiles
    version: 1.3.2

  - name: xiple.rpmfusion
    src: https://github.com/xiple/ansible-role-rpmfusion

  - name: xiple.tailscale
    src: https://github.com/xiple/ansible-role-tailscale

  - name: xiple.vscode
    src: https://github.com/xiple/ansible-role-vscode

  - name: xiple.nordvpn
    src: https://github.com/xiple/ansible-role-nordvpn

